### ISSUE TITLE
The shape topology to Mermaid

### ISSUE THREAD

**Issue by pietercolpaert** [TREEcg/extract-cbd-shape#29]
It would be useful to be able to export the shape topology as a mermaid description.

I.e., the shape topology

```javascript
Shape {
   atLeastOneLists: [ Shape {
       requiredPaths: ["gsp:geo asWKT|asGML", "^foaf:member"],
       optionalPaths: ["foaf:knows"]
   },
   Shape {
    //...
   }]
} 
```

Could be translated to this in mermaid:
```
flowchart TD
    S(( ))-->X{ }
    X-->S1(( ))
    X-->S2(( ))
    S1-->|gsp:geo|S3[ ]-->|"asWKT | asGML"|S4[ ]
    S5[ ]-->|^foaf:member|S1
    S1-.->|foaf:knows|S6[ ]
```

Visualizing into:
```mermaid
flowchart TD
    S(( ))-->X{ }
    X-->S1(( ))
    X-->S2(( ))
    S1-->|gsp:geo|S3[ ]-->|"asWKT | asGML"|S4[ ]
    S5[ ]-->|^foaf:member|S1
    S1-.->|foaf:knows|S6[ ]
```

**Comment by pietercolpaert** [comment]
```
import {CBDShapeExtractor} from "extract-cbd-shape";
// This will create the shape topology already
// ShapesGraph is an rdf-stores RDFStore containing all quads 
let extractor = new CBDShapeExtractor(shapesGraph);
//This now has something of type [ShapesGraph](https://github.com/TREEcg/extract-cbd-shape/blob/main/lib/Shape.ts#L193) in it, in which I’d like to add a toMermaid function that takes the term of the nodeshape as a parameter
extractor.shapesGraph.toMermaid(df.namedNode('nodeshapeIRI'));
```

**Comment by pheyvaer** [comment]
@pietercolpaert How would you convert something like this shape to Mermaid?
```turtle
ex:Shape a sh:NodeShape ;
    sh:property [
        sh:path ex:subject ;
        sh:minCount 1 ;
        sh:node [
            sh:property [
                sh:path rdfs:label ;
                sh:minCount 1
            ]
        ]
    ] .
```
When it's converted to a Shape topology it has both `requiredPaths` and `nodeLinks`, and both mention `ex:subject`.

**Comment by pietercolpaert** [comment]
A nodelink path is also going to be repeated in either the optional or in the required path indeed. So I’d say if a path is already processed as part of a nodelink, let’s ignore it in the optional/required, unless we will also visualize required vs. optional in a different way, i.e. by using a dashed line instead of a full line?

**Comment by pheyvaer** [comment]
Ok! I included that. 

Another question: how do we deal with double inverse paths? 

```turtle
ex:DoubleInversePathShape a sh:NodeShape ;
    sh:closed true;
    sh:property [
        sh:path ([sh:inversePath [sh:inversePath ex:p1 ] ]) ;
        sh:minCount 1
    ] .
```
Do we just invert the first inverse path and leave the second as is (which is what happens now) or do we keep inverting them until we can't anymore? 

P.S. I don't fully understand why someone would use a double inverse path in the first place 😄

**Comment by pietercolpaert** [comment]
I believe we should turn it around again indeed: double inverse becomes forward

**Comment by pheyvaer** [comment]
Closed by https://github.com/TREEcg/extract-cbd-shape/pull/30
