### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by pietercolpaert** [TREEcg/extract-cbd-shape#6]
We should have performance tests for:

1. In-band entities
    1. Extracting an entity with CBD only
    2. Extracting an entity with named graphs only
    3. Extracting an entity with CBD + named graphs
    4. Extracting an entity with a simple shape not adding anything beyond CBD
    5. Extracting an entity with various complex paths in the shape
    6. Extracting an entity with various complex paths in the shape and conditionals
2. out of band entities
    1. Without shape: no quads were found
    2. A required path is not set in the shape
    3. A required path is not set in none of the conditionals in the shape

The test should extract the entity ~100 times and measure how long it took. The results should be automatically summarized in a table. Github CI integrations would be nice

**Comment by pietercolpaert** [comment]
Thought I had I quickly want to document: the same object and the same amount of quads should be extracted if we put something in 1 chart -- otherwise it’s not a fair comparison. It’s indeed going to be faster to extract 5 triples using CBD, than extracting 20 triples using a shape -- but also CBD would be slower on those 20 triples

**Comment by xdxxxdx** [comment]
- With Commit: https://github.com/TREEcg/extract-cbd-shape/commit/ff22863fa0279ea005ce7fc2a0d7f32921d5e113 
- GitHub action added to auto-run the inband performance testing and add the result to : https://github.com/TREEcg/extract-cbd-shape/blob/gh-pages/docs/data.js
    - GitHub action is triggered by push on the fix-perf branch
    - The GitHub page allows to keep track of the performance after each commit, the ideal result will be as https://benchmark-action.github.io/github-action-benchmark/dev/bench/
    - Current result: https://treecg.github.io/extract-cbd-shape/
![image](https://github.com/TREEcg/extract-cbd-shape/assets/15314807/214a3edf-d9ed-4406-b65f-5276bae61fb3)
   - Alert created if there is performance decrease: https://github.com/TREEcg/extract-cbd-shape/commit/4cc6c8039791a951e32848bc50bd4a5fea46b11c#commitcomment-136305765
![image](https://github.com/TREEcg/extract-cbd-shape/assets/15314807/e73411d3-3603-45ba-a903-b556feaf5fbc)

**Comment by pietercolpaert** [comment]
Love it!
